# Home Assistant Configuration
# Managed by Ansible

# Load default integrations
default_config:

# Basic settings
homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Warsaw

# HTTP Configuration for reverse proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:         
    - 10.99.0.0/24

# Configuration for HACS docker monitoring extension 
# Example configuration.yaml entry
monitor_docker:
  - name: Docker
    containers:
      - n8n
      - joplin-app
      - excalidraw
      - octoprint
    rename:
      joplin-app: joplin
    monitored_conditions:
      - version
      - containers_running
      - containers_total
      - state
      - status
      - memory