# Home Assistant Configuration
# Managed by Ansible

# Load default integrations
default_config:

# Basic settings
homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Warsaw

# HTTP Configuration for reverse proxy
http:
  use_x_forwarded_for: true
  base_url: "http://192.168.0.171/haos"
  trusted_proxies:
    - 192.168.0.0/24     # Entire subnet
    - 172.16.0.0/12      # Docker networks
    - 127.0.0.1          # Localhost
    - "proxy"         
    - 10.99.0.0/24