- name: Prepare service
  include_role:
    name: docker
    tasks_from: prepare_env
  vars:
    service_port: "{{ octoprint_port }}"
    service_name: "octoprint"
    service_dir: "{{ octoprint_files_path }}"

- name: Start octoprint container
  community.docker.docker_container:
    name: "octoprint"
    image: "octoprint/octoprint:latest"
    state: started
    restart_policy: "unless-stopped"
    ports:
      - "{{ octoprint_port }}:80"
    volumes:
      - "{{ octoprint_files_path }}:/octoprint/octoprint"
      - "/dev:/dev"

- name: Verify service
  include_role:
    name: docker
    tasks_from: verify_env
  vars:
    service_port: "{{ octoprint_port }}"
    service_name: "octoprint"

- name: Configure OctoPrint serial port
  blockinfile:
    path: "{{ octoprint_files_path }}/octoprint/config.yaml"
    marker: "# {mark} ANSIBLE OCTOPRINT SERIAL CONFIG"
    insertafter: '^serial:'
    block: |
      port: {{ octoprint_3dprinter_device_path }}
      baudrate: 250000
      autoconnect: true
  failed_when: false

- name: Add Samba share
  include_role: 
    name: samba
    tasks_from: add_samba_share
  vars:
    share_name: gcodes
    share_path: "{{ octoprint_files_path }}/uploads"
    share_service_name: octoprint