#configure directories for cypress tests
- name: Creates directory if not exist
  ansible.builtin.file:
    path: /actions-runner/files/cypress
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Check if any config files exist in directory
  ansible.builtin.find:
    paths: /actions-runner/files/cypress/
    patterns: "*.js"
  register: cypress_config_file

- name: Copy configs if directory is empty
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: /actions-runner/files/cypress/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  when: cypress_config_file.matched == 0
  loop:
    - hello_world.cy.js
    - cypress.config.js