- name: Create {{ service_name }} directory
  file:
    path: "{{ service_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Ensure proxy network exists
  community.docker.docker_network:
    name: proxy
    state: present