- name: Create {{ service_name }} directory
  file:
    path: "{{ service_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Allow {{ service_name }} port on UFW
  community.general.ufw:
    rule: allow
    port: "{{ service_port }}"
    proto: tcp