all:
  hosts:
    local:
      localhost:
        ansible_connection: local
    remote:
      rpi:
        ansible_host: 192.168.0.10
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  vars:
    ansible_user: rpi
    path_to_repo: /actions-runner/repos/rpi-virtualisation-infra-ansible/rpi-virtualisation-infra-ansible/