#example use: ansible-playbook run_cypress_tests.yml -e "cypress_test_file=hello_world.cy.js"
- name: run test
  hosts: localhost
  tasks:
    - name: run cypress test
      include_role: 
        name: cypress
        tasks_from: run_test
