- name: run containers 
  hosts: localhost
  roles:
    - role: docker
      tags: [always]
    - role: klipper
      tags: [klipper]
    - role: n8n
      tags: [n8n]
    - role: haos
      tags: [haos]
    - role: alerts
      tags: [alerts]
    - role: [cypress]
      tags: cypress
