- name: run roles which needs to run on the system
  hosts: localhost
  roles:
    - role: firewall
      tags: [always]
    - role: reverse-proxy
      tags: [always]
    - role: cockpit
      tags: [always]
    - role: samba
      tags: [always]
