n8n_port: "5678"
n8n_files_path: "/actions-runner/files/n8n"
n8n_repo_path: "/actions-runner/repos/rpi-automation-services-n8n/rpi-automation-services-n8n/"

n8n_owner_email: admin@example.com
n8n_owner_first_name:  admin 
n8n_owner_last_name: user
n8n_owner_password: Password1