services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - proxy
    volumes:
      - /actions-runner/files/alerts/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /actions-runner/files/alerts/config/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.prometheus.rule: "PathPrefix(`/prometheus`)"
      traefik.http.routers.prometheus.entrypoints: "web"
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"
      traefik.http.middlewares.prometheus-stripprefix.stripprefix.prefixes: "/prometheus"
      traefik.http.routers.prometheus.middlewares: "prometheus-stripprefix"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    networks:
      - proxy
    volumes:
      - /actions-runner/files/alerts/config/alertmanager.yml:/etc/alertmanager/config.yml:ro
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.alertmanager.rule: "PathPrefix(`/alertmanager`)"
      traefik.http.routers.alertmanager.entrypoints: "web"
      traefik.http.services.alertmanager.loadbalancer.server.port: "9093"
      traefik.http.middlewares.alertmanager-stripprefix.stripprefix.prefixes: "/alertmanager"
      traefik.http.routers.alertmanager.middlewares: "alertmanager-stripprefix"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    networks:
      - proxy
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.cadv.rule: "Host(`cadv.local`)"
      traefik.http.routers.cadv.entrypoints: "web"
      traefik.http.services.cadv.loadbalancer.server.port: "8080"

networks:
  proxy:
    external: true
  alerts-net:
