- name: Ensure directories for containers exists
  ansible.builtin.file:
    path: /actions-runner/files/alerts/config
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Check if any config files exist in directory
  ansible.builtin.find:
    paths: /actions-runner/files/alerts/config/
    patterns: "*yml"
  register: existing_config_files

- name: Copy configs if directory is empty
  ansible.builtin.copy:
    src: "{{ role_path }}/files/config/"
    dest: /actions-runner/files/alerts/config/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  when: existing_config_files.matched == 0

- name: start containers from docker-compose file
  community.docker.docker_compose_v2:
    project_src: "{{ role_path }}/files"
    state: present

- name: Allow alerting services through firewall
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    comment: 'alerting services'
  loop:
    - "9090"
    - "9093"
    - "8082"
    - "9100"
