- name: Prepare service
  include_role:
    name: docker
    tasks_from: prepare_env
  vars:
    service_name: "alerts"
    service_dir: "/actions-runner/files/alerts/config"

- name: Check if any config files exist in directory
  ansible.builtin.find:
    paths: /actions-runner/files/alerts/config/
    patterns: "*yml"
  register: existing_config_files

- name: Copy configs if directory is empty
  ansible.builtin.copy:
    src: "{{ role_path }}/files/config/"
    dest: /actions-runner/files/alerts/config/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  when: existing_config_files.matched == 0

- name: start containers from docker-compose file
  community.docker.docker_compose_v2:
    project_src: "{{ role_path }}/files"
    state: present

- name: Verify service
  include_role:
    name: docker
    tasks_from: verify_compose_env
  vars:
    service_name: "alerts"
